server:
  port: 9002
spring:
  application:
    name: kobep-jpa
  datasource:
    kobepjpa:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/kobep?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
  jackson:
    date-forma: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



