server:
  port: 9005
spring:
  application:
    name: kobep-gateway
  main:
    allow-bean-definition-overriding: true
  # 加上此配置可自动配置安全验证及JWT验证
#  autoconfigure:
#    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8090/uaa/token_keys
  redis:
    #数据库索引
    host:  182.92.243.231
    port:  6379
    database:  0
    password:  skypxd
    timeout: 60s
    lettuce:
      pool:
        #最大连接数
        max-active: 400
        max-idle: 100
        max-wait: -1ms
        #最小空闲
        min-idle: 20
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启通过服务中心的自动根据 serviceId 创建路由，路由serviceId为大写
          lower-case-service-id: true
      routes:
        - id: kobep-jpa
          uri: lb://kobep-jpa
          predicates:
            - Path=/kobepjpa/**
          filters:
#            - GwSwaggerHeaderFilter
            - StripPrefix=1
        - id: kobep-back
          uri: lb://kobep-back
          predicates:
            - Path=/kobepback/**
          filters:
#            - GwSwaggerHeaderFilter
            - StripPrefix=1
        - id: kobep-auth
          uri: lb://kobep-auth
          predicates:
            - Path=/kobepauth/**
          filters:
#            - GwSwaggerHeaderFilter
            - StripPrefix=1
